### Pandas

In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\harsh\onedrive\desktop\pythonkn\venv\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in c:\users\harsh\onedrive\desktop\pythonkn\venv\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\harsh\onedrive\desktop\pythonkn\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\harsh\onedrive\desktop\pythonkn\venv\lib\site-packages (from pandas) (2026.3.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\harsh\onedrive\desktop\pythonkn\venv\lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\users\harsh\onedrive\desktop\pythonkn\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [1]:
import pandas as pd

In [2]:
# Series 
# Series with the help of list
data=[1,2,3,4]
series= pd.Series(data)
print("Series: \n",series)
print(type(series))

Series:
 0    1
1    2
2    3
3    4
dtype: int64
<class 'pandas.core.series.Series'>

In [4]:
# Series with the help of Dictionary
data={'a':1, 'b':2, 'c':3,'d':4}
d_series= pd.Series(data)
print("series: \n",d_series)

series:
 a    1
b    2
c    3
d    4
dtype: int64

In [5]:
data=[7,8,9]
idx=['i','ii','iii']
pd.Series(data, index=idx)

i      7
ii     8
iii    9
dtype: int64

In [6]:
#DataFrame
#Create a dataframe from dictionary of list
data={
  'Name':['Harsh', 'Yash', 'Ayush'],
  'Age':[20, 19, 17],
  'city':['Florida', 'New york', 'Bangalore']
}
idx=['a','b','c']
df= pd.DataFrame(data, index=idx)
print(df)
print(type(df))

    Name  Age       city
a  Harsh   20    Florida
b   Yash   19   New york
c  Ayush   17  Bangalore
<class 'pandas.core.frame.DataFrame'>

In [7]:
import numpy as np
np.array(df)

array([['Harsh', 20, 'Florida'],
       ['Yash', 19, 'New york'],
       ['Ayush', 17, 'Bangalore']], dtype=object)

In [8]:
# Create a dataframe from list of Dictionary
data=[
  {'Name': "harsh", 'Age': 20, 'City': 'Bangalore'},
  {'Name': 'Yash', 'Age': 19, 'City': 'New York'},
  {'Name': 'Ayush', 'Age': 17, 'City': 'Florida'}
]
df= pd.DataFrame(data)
print(df)

    Name  Age       City
0  harsh   20  Bangalore
1   Yash   19   New York
2  Ayush   17    Florida

In [9]:
import pandas as pd

#top 5 records
df=pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [10]:
#last 5 records
df.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [11]:
#Access data from dataframe
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [12]:
#Access data from dataframe
df['Region']

0      North America
1             Europe
2               Asia
3      North America
4             Europe
           ...
235           Europe
236             Asia
237    North America
238           Europe
239             Asia
Name: Region, Length: 240, dtype: object

In [13]:
#all data of 0th row using loc() method
df.loc[0]

Transaction ID              10001
Date                   2024-01-01
Product Category      Electronics
Product Name        iPhone 14 Pro
Units Sold                      2
Unit Price                 999.99
Total Revenue             1999.98
Region              North America
Payment Method        Credit Card
Name: 0, dtype: object

In [14]:
df.iloc[0][5:]

Unit Price               999.99
Total Revenue           1999.98
Region            North America
Payment Method      Credit Card
Name: 0, dtype: object

In [17]:
# accessing element using at()
df.at[1, 'Region']

'Europe'

In [19]:
# Accessing a specified using iat()work like accessing element in matrix(0-based indexing )
df.iat[1,2]

'Home Appliances'

In [29]:
data=[
  {'Name': "harsh", 'Age': 20, 'City': 'Bangalore'},
  {'Name': 'Yash', 'Age': 19, 'City': 'New York'},
  {'Name': 'Ayush', 'Age': 17, 'City': 'Florida'}
]
df= pd.DataFrame(data)
print(df)

    Name  Age       City
0  harsh   20  Bangalore
1   Yash   19   New York
2  Ayush   17    Florida

In [30]:
# Adding a column
df['salary']= [2000,3000,4000]
df

    Name  Age       City  salary
0  harsh   20  Bangalore    2000
1   Yash   19   New York    3000
2  Ayush   17    Florida    4000

In [31]:
# deleting a column with drop() and it is not permanent operation it's temp. operations
df.drop('salary', axis=1, inplace=True)

In [32]:
df

    Name  Age       City
0  harsh   20  Bangalore
1   Yash   19   New York
2  Ayush   17    Florida

In [35]:
#Adding +1 to Age for every age present
df['Age']= df['Age']+1
df

    Name  Age       City
0  harsh   23  Bangalore
1   Yash   22   New York
2  Ayush   20    Florida

In [1]:
import pandas as pd
df= pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [3]:
#Display the type of each column
print("Data type:\n", df.dtypes)

#Describe the dataframe
print("Statistical summary: ", df.describe())

# #Group by column and perform aggregation
# grouped= df.groupby('Category')['Value'].mean()
# print("Mean value by category: \n", grouped)

Data type:
 Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object
Statistical summary:         Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [4]:
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

## working on wine.csv file

In [5]:
import pandas as pd

In [8]:
df=pd.read_csv('wine.csv')
df.head(5)

,Unnamed: 0,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [9]:
df.tail(5)

,Unnamed: 0,0,1,2,3,4,5,6,7,8,9,10,11,12,13
173,173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.7,0.64,1.74,740
174,174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.3,0.70,1.56,750
175,175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.2,0.59,1.56,835
176,176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.3,0.60,1.62,840
177,177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.2,0.61,1.60,560

In [10]:
df.isnull()

,Unnamed: 0,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
174,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
175,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
176,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
177,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [11]:
df.isnull().sum()

Unnamed: 0    0
0             0
1             0
2             0
3             0
4             0
5             0
6             0
7             0
8             0
9             0
10            0
11            0
12            0
13            0
dtype: int64

In [12]:
df.isnull().mean()

Unnamed: 0    0.0
0             0.0
1             0.0
2             0.0
3             0.0
4             0.0
5             0.0
6             0.0
7             0.0
8             0.0
9             0.0
10            0.0
11            0.0
12            0.0
13            0.0
dtype: float64

In [14]:
df['0']

0      1
1      1
2      1
3      1
4      1
      ..
173    3
174    3
175    3
176    3
177    3
Name: 0, Length: 178, dtype: int64

In [16]:
df.loc[0]

Unnamed: 0       0.00
0                1.00
1               14.23
2                1.71
3                2.43
4               15.60
5              127.00
6                2.80
7                3.06
8                0.28
9                2.29
10               5.64
11               1.04
12               3.92
13            1065.00
Name: 0, dtype: float64